// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// getTau2Loh
NumericVector getTau2Loh(const NumericVector x, const NumericVector y, const NumericVector onset, const NumericVector r_low, const NumericVector r, const IntegerVector index, const IntegerVector importT1, const IntegerVector importT2);
RcppExport SEXP _tauodds_getTau2Loh(SEXP xSEXP, SEXP ySEXP, SEXP onsetSEXP, SEXP r_lowSEXP, SEXP rSEXP, SEXP indexSEXP, SEXP importT1SEXP, SEXP importT2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type onset(onsetSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type r_low(r_lowSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< const IntegerVector >::type index(indexSEXP);
    Rcpp::traits::input_parameter< const IntegerVector >::type importT1(importT1SEXP);
    Rcpp::traits::input_parameter< const IntegerVector >::type importT2(importT2SEXP);
    rcpp_result_gen = Rcpp::wrap(getTau2Loh(x, y, onset, r_low, r, index, importT1, importT2));
    return rcpp_result_gen;
END_RCPP
}
// getTau2Lohv2
NumericVector getTau2Lohv2(const NumericVector x, const NumericVector y, const NumericVector onset, const NumericVector r_low, const NumericVector r, const IntegerVector index, const IntegerVector importT1, const IntegerVector importT2);
RcppExport SEXP _tauodds_getTau2Lohv2(SEXP xSEXP, SEXP ySEXP, SEXP onsetSEXP, SEXP r_lowSEXP, SEXP rSEXP, SEXP indexSEXP, SEXP importT1SEXP, SEXP importT2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type onset(onsetSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type r_low(r_lowSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< const IntegerVector >::type index(indexSEXP);
    Rcpp::traits::input_parameter< const IntegerVector >::type importT1(importT1SEXP);
    Rcpp::traits::input_parameter< const IntegerVector >::type importT2(importT2SEXP);
    rcpp_result_gen = Rcpp::wrap(getTau2Lohv2(x, y, onset, r_low, r, index, importT1, importT2));
    return rcpp_result_gen;
END_RCPP
}
// getTau2OddsMeasles
NumericVector getTau2OddsMeasles(const NumericVector x, const NumericVector y, const NumericVector onset, const NumericVector r_low, const NumericVector r, const IntegerVector index, const IntegerVector importT1, const IntegerVector importT2);
RcppExport SEXP _tauodds_getTau2OddsMeasles(SEXP xSEXP, SEXP ySEXP, SEXP onsetSEXP, SEXP r_lowSEXP, SEXP rSEXP, SEXP indexSEXP, SEXP importT1SEXP, SEXP importT2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type onset(onsetSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type r_low(r_lowSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< const IntegerVector >::type index(indexSEXP);
    Rcpp::traits::input_parameter< const IntegerVector >::type importT1(importT1SEXP);
    Rcpp::traits::input_parameter< const IntegerVector >::type importT2(importT2SEXP);
    rcpp_result_gen = Rcpp::wrap(getTau2OddsMeasles(x, y, onset, r_low, r, index, importT1, importT2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tauodds_getTau2Loh", (DL_FUNC) &_tauodds_getTau2Loh, 8},
    {"_tauodds_getTau2Lohv2", (DL_FUNC) &_tauodds_getTau2Lohv2, 8},
    {"_tauodds_getTau2OddsMeasles", (DL_FUNC) &_tauodds_getTau2OddsMeasles, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_tauodds(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
