# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getTau2Loh <- function(x, y, onset, r_low, r, index, importT1, importT2) {
    .Call(`_tauodds_getTau2Loh`, x, y, onset, r_low, r, index, importT1, importT2)
}

getTau2Lohv2 <- function(x, y, onset, r_low, r, index, importT1, importT2) {
    .Call(`_tauodds_getTau2Lohv2`, x, y, onset, r_low, r, index, importT1, importT2)
}

getTau2OddsMeasles <- function(x, y, onset, r_low, r, index, importT1, importT2) {
    .Call(`_tauodds_getTau2OddsMeasles`, x, y, onset, r_low, r, index, importT1, importT2)
}

